"""Sidecar ↔ Electron JSON Lines 协议常量（阶段 1 冻结）。"""
from __future__ import annotations

from enum import Enum

PROTOCOL_VERSION = 1
APP_NAME = "Downany"
APP_VERSION = "0.2.0"


class MessageType(str, Enum):
    REQUEST = "request"
    RESPONSE = "response"
    EVENT = "event"
    HELLO = "hello"


class Method(str, Enum):
    APP_GET_SNAPSHOT = "app.getSnapshot"
    APP_PING = "app.ping"
    APP_SHUTDOWN = "app.shutdown"
    APP_RUN_MIGRATION = "app.runMigration"
    APP_EXPORT_DIAGNOSTICS = "app.exportDiagnostics"
    DOWNLOAD_PARSE_URLS = "download.parseUrls"
    DOWNLOAD_CANCEL_PARSE = "download.cancelParse"
    DOWNLOAD_CREATE_TASKS = "download.createTasks"
    DOWNLOAD_PAUSE = "download.pause"
    DOWNLOAD_PAUSE_ALL = "download.pauseAll"
    DOWNLOAD_RESUME = "download.resume"
    DOWNLOAD_RESUME_ALL = "download.resumeAll"
    DOWNLOAD_CANCEL = "download.cancel"
    DOWNLOAD_RETRY = "download.retry"
    DOWNLOAD_REMOVE = "download.remove"
    DOWNLOAD_REMOVE_GROUP = "download.removeGroup"
    DOWNLOAD_CLEAR_FINISHED = "download.clearFinished"
    DOWNLOAD_UPDATE_TASK = "download.updateTask"
    DOWNLOAD_REORDER = "download.reorder"
    SEARCH_QUERY = "search.query"
    HISTORY_LIST = "history.list"
    HISTORY_DELETE = "history.delete"
    HISTORY_CLEAR = "history.clear"
    SETTINGS_GET = "settings.get"
    SETTINGS_UPDATE = "settings.update"
    UPDATER_CHECK_YTDLP = "updater.checkYtDlp"
    UPDATER_CHECK_HEALTH = "updater.checkHealth"
    UPDATER_UPDATE_YTDLP = "updater.updateYtDlp"
    TELEGRAM_GET_CONFIG = "telegram.getConfig"
    TELEGRAM_CONFIGURE = "telegram.configure"
    TELEGRAM_LIST_DELIVERIES = "telegram.listDeliveries"
    TELEGRAM_CLAIM_NEXT = "telegram.claimNext"
    TELEGRAM_RENEW_LEASE = "telegram.renewLease"
    TELEGRAM_RELEASE_CLAIM = "telegram.releaseClaim"
    TELEGRAM_MARK_SENDING = "telegram.markSending"
    TELEGRAM_SET_SEGMENT_MANIFEST = "telegram.setSegmentManifest"
    TELEGRAM_MARK_SEGMENT_SENT = "telegram.markSegmentSent"
    TELEGRAM_MARK_FALLBACK_USED = "telegram.markFallbackUsed"
    TELEGRAM_MARK_SENT = "telegram.markSent"
    TELEGRAM_MARK_RETRY = "telegram.markRetry"
    TELEGRAM_MARK_RETRY_NOT_SUBMITTED = "telegram.markRetryNotSubmitted"
    TELEGRAM_MARK_FAILED = "telegram.markFailed"
    TELEGRAM_MARK_UNCERTAIN = "telegram.markUncertain"
    TELEGRAM_MARK_SKIPPED_OVERSIZE = "telegram.markSkippedOversize"
    TELEGRAM_MARK_TARGET_FAILED = "telegram.markTargetFailed"
    TELEGRAM_RETRY = "telegram.retry"
    TELEGRAM_CANCEL_PENDING = "telegram.cancelPending"
    TELEGRAM_GET_TARGET_BLOCK = "telegram.getTargetBlock"
    TELEGRAM_CLEAR_TARGET_BLOCK = "telegram.clearTargetBlock"


class EventName(str, Enum):
    TASK_ADDED = "task.added"
    TASK_UPDATED = "task.updated"
    TASK_PROGRESS = "task.progress"
    TASK_COMPLETED = "task.completed"
    TASK_FAILED = "task.failed"
    TASK_REMOVED = "task.removed"
    PARSE_RESULT = "download.parseResult"
    SEARCH_RESULT = "search.result"
    HISTORY_CHANGED = "history.changed"
    SETTINGS_CHANGED = "settings.changed"
    SIDECAR_HEALTH = "sidecar.health"
    TELEGRAM_DELIVERY_QUEUED = "telegramDelivery.queued"
    TELEGRAM_DELIVERY_UPDATED = "telegramDelivery.updated"
    TELEGRAM_DELIVERY_SENT = "telegramDelivery.sent"
    TELEGRAM_DELIVERY_FAILED = "telegramDelivery.failed"
    TELEGRAM_DELIVERY_UNCERTAIN = "telegramDelivery.uncertain"


class ErrorCode(str, Enum):
    INVALID_MESSAGE = "INVALID_MESSAGE"
    PROTOCOL_MISMATCH = "PROTOCOL_MISMATCH"
    METHOD_NOT_FOUND = "METHOD_NOT_FOUND"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    INVALID_PARAMS = "INVALID_PARAMS"
    INTERNAL = "INTERNAL"
