"""
把 HTTP Cookie 头落到 Netscape cookiefile，供 yt-dlp cookiejar 使用。

Instagram 等 extractor 用 `_get_cookies()` / `_is_logged_in` 读的是 cookiejar，
仅设 `http_headers['Cookie']` 不会被视为已登录。
"""
from __future__ import annotations

import os
import tempfile
from typing import Any, Dict, Mapping, Optional
from urllib.parse import urlparse


def cookiefile_domain_for_url(url: str) -> str:
    """Netscape 域：带前导点以便覆盖子域。"""
    try:
        host = (urlparse(url).hostname or "").lower().strip(".")
    except Exception:
        host = ""
    if not host:
        return ""
    # 去掉常见 www. 前缀，写成 .example.com
    if host.startswith("www."):
        host = host[4:]
    return "." + host


def cookie_header_to_netscape(cookie_header: str, domain: str) -> str:
    """Cookie 请求头 → Netscape HTTP Cookie File 文本。"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by VideoDownloader for yt-dlp",
    ]
    domain = (domain or "").strip() or ".localhost"
    for part in (cookie_header or "").split(";"):
        piece = part.strip()
        if not piece or "=" not in piece:
            continue
        name, value = piece.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name:
            continue
        # domain \t include_subdomains \t path \t secure \t expires \t name \t value
        lines.append(f"{domain}\tTRUE\t/\tTRUE\t0\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def materialize_cookiefile(cookie_header: str, url: str) -> Optional[str]:
    """
    将 Cookie 头写入临时 Netscape 文件，返回路径。
    调用方负责在下载结束后删除文件。
    """
    header = (cookie_header or "").strip()
    if not header:
        return None
    domain = cookiefile_domain_for_url(url)
    if not domain:
        return None
    body = cookie_header_to_netscape(header, domain)
    fd, path = tempfile.mkstemp(prefix="videodl-cookies-", suffix=".txt")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(body)
    except Exception:
        try:
            os.unlink(path)
        except OSError:
            pass
        raise
    return path


def extract_cookie_header(http_headers: Optional[Mapping[str, Any]]) -> str:
    if not isinstance(http_headers, Mapping):
        return ""
    for key, value in http_headers.items():
        if str(key).lower() == "cookie" and value:
            return str(value).strip()
    return ""


def apply_cookiefile_from_headers(
    ydl_opts: Dict[str, Any],
    url: str,
) -> Optional[str]:
    """
    若 opts 含 Cookie 头且尚未设置 cookiefile，则写入临时文件并挂上。
    成功后从 http_headers 移除 Cookie（避免弃用警告，并让 jar 成为唯一来源）。
    返回临时路径（需清理），无则 None。
    """
    if ydl_opts.get("cookiefile"):
        return None
    header = extract_cookie_header(ydl_opts.get("http_headers"))
    if not header:
        return None
    path = materialize_cookiefile(header, url)
    if path:
        ydl_opts["cookiefile"] = path
        headers = ydl_opts.get("http_headers")
        if isinstance(headers, dict):
            ydl_opts["http_headers"] = {
                k: v for k, v in headers.items() if str(k).lower() != "cookie"
            }
    return path


def cleanup_cookiefile(path: Optional[str]) -> None:
    if not path:
        return
    try:
        os.unlink(path)
    except OSError:
        pass
