<#
.SYNOPSIS
  Build the pinned official Telegram Bot API server for Windows x64.

.DESCRIPTION
  This is the only supported Windows staging entry point for the local Bot API.
  It deliberately fails before touching the repository when the Visual Studio /
  CMake toolchain is unavailable.  Source, vcpkg and build directories are all
  contained below .build; the resource directory is validated before any child
  is removed.  No token or app credential is generated by this script.
#>

[CmdletBinding()]
param(
    [string]$WorkspaceRoot = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Fail([string]$Message) {
    throw "Telegram Bot API Windows build failed: $Message"
}

function Get-FullPath([string]$Path) {
    if ([string]::IsNullOrWhiteSpace($Path)) { Fail "path is empty" }
    return [System.IO.Path]::GetFullPath($Path)
}

function Assert-Contained([string]$Child, [string]$Parent, [string]$Label) {
    $childFull = Get-FullPath $Child
    $parentFull = (Get-FullPath $Parent).TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
    if (-not $childFull.StartsWith($parentFull, [System.StringComparison]::OrdinalIgnoreCase)) { Fail "$Label escaped its containment root" }
    return $childFull
}

function Assert-NoReparseRoot([string]$Path, [string]$Label) {
    if (-not (Test-Path -LiteralPath $Path)) { return }
    $item = Get-Item -LiteralPath $Path -Force
    if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
        Fail "$Label is a reparse point: $Path"
    }
}

function Clear-ContainedDirectory([string]$Path, [string]$BuildRoot, [string]$Label) {
    $resolved = Assert-Contained $Path $BuildRoot $Label
    if (-not (Test-Path -LiteralPath $resolved)) {
        New-Item -ItemType Directory -Path $resolved -Force | Out-Null
        return
    }
    Assert-NoReparseRoot $resolved $Label
    $children = @(Get-ChildItem -LiteralPath $resolved -Force)
    foreach ($child in $children) {
        if (($child.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            Fail "$Label contains a reparse-point child: $($child.FullName)"
        }
        Assert-Contained $child.FullName $resolved "$Label child" | Out-Null
    }
    foreach ($child in $children) {
        if ($child.Name -eq ".gitkeep") { continue }
        Remove-Item -LiteralPath $child.FullName -Recurse -Force
    }
}

function Invoke-Checked([string]$FilePath, [string[]]$Arguments, [string]$Label) {
    Write-Host "==> $Label"
    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) { Fail "$Label exited with $LASTEXITCODE" }
}

function Require-Command([string]$Name) {
    $command = Get-Command $Name -ErrorAction SilentlyContinue
    if (-not $command -or -not $command.Source) { Fail "missing required command: $Name" }
    return (Get-FullPath $command.Source)
}

if ([string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
    $WorkspaceRoot = Split-Path -Parent $PSScriptRoot
}
$WorkspaceRoot = (Resolve-Path -LiteralPath $WorkspaceRoot).Path
if (-not (Test-Path -LiteralPath (Join-Path $WorkspaceRoot ".git"))) { Fail "WorkspaceRoot is not the repository root" }

$lockPath = Join-Path $WorkspaceRoot "packaging\telegram-bot-api\source.lock.json"
$manifestRoot = Join-Path $WorkspaceRoot "packaging\telegram-bot-api"
$buildRoot = Join-Path $WorkspaceRoot ".build\telegram-bot-api"
$windowsBuildRoot = Join-Path $buildRoot "windows"
$sourceRoot = Join-Path $windowsBuildRoot "source"
$sourceBuildRoot = Join-Path $windowsBuildRoot "source-build"
$vcpkgRoot = Join-Path $WorkspaceRoot ".build\vcpkg"
$vcpkgInstalledRoot = Join-Path $WorkspaceRoot ".build\vcpkg_installed"
$stageRoot = Join-Path $windowsBuildRoot "stage"
$resourceRoot = Join-Path $WorkspaceRoot "desktop\resources\telegram-bot-api"
$git = Require-Command "git.exe"
$cmake = Require-Command "cmake.exe"
$vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path -LiteralPath $vswhere)) { Fail "VS2022 vswhere.exe is missing" }
$vswhere = (Resolve-Path -LiteralPath $vswhere).Path

$lock = Get-Content -LiteralPath $lockPath -Raw -Encoding utf8 | ConvertFrom-Json
if ($lock.schemaVersion -ne 1 -or $lock.targets -notcontains "win32-x64") { Fail "source.lock.json is not the expected schema/target" }
if ($lock.windowsVcpkgTriplet -ne "x64-windows-static") { Fail "source.lock.json must use x64-windows-static" }
if ($lock.commit -notmatch "^[0-9a-f]{40}$" -or $lock.vcpkgBaseline -notmatch "^[0-9a-f]{40}$") { Fail "source lock contains an invalid commit" }

Assert-Contained $windowsBuildRoot $buildRoot "Windows build root" | Out-Null
Assert-Contained $sourceRoot $windowsBuildRoot "source root" | Out-Null
Assert-Contained $sourceBuildRoot $windowsBuildRoot "source build root" | Out-Null
Assert-Contained $stageRoot $windowsBuildRoot "stage root" | Out-Null
Assert-Contained $resourceRoot (Join-Path $WorkspaceRoot "desktop\resources") "resource root" | Out-Null
Assert-NoReparseRoot $buildRoot ".build/telegram-bot-api"
Assert-NoReparseRoot $resourceRoot "Telegram resource root"

$vsInstallation = (& $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath | Select-Object -First 1).Trim()
if ([string]::IsNullOrWhiteSpace($vsInstallation) -or -not (Test-Path -LiteralPath $vsInstallation)) {
    Fail "VS2022 C++ x64 workload is missing"
}

# Verify the toolchain before any clone/build/staging mutation.
& $cmake --version | Select-Object -First 1 | Write-Host
$vcpkgSource = Join-Path $vcpkgRoot "vcpkg.exe"
$vcpkgBootstrap = Join-Path $vcpkgRoot "bootstrap-vcpkg.bat"
if (-not (Test-Path -LiteralPath $vcpkgRoot)) {
    Assert-Contained $vcpkgRoot (Join-Path $WorkspaceRoot ".build") "vcpkg root" | Out-Null
    Invoke-Checked $git @("clone", "--no-checkout", [string]$lock.vcpkgRepository, $vcpkgRoot) "clone vcpkg"
}
Assert-NoReparseRoot $vcpkgRoot "vcpkg root"
Invoke-Checked $git @("-C", $vcpkgRoot, "fetch", "--depth", "1", "origin", [string]$lock.vcpkgBaseline) "fetch pinned vcpkg baseline"
Invoke-Checked $git @("-C", $vcpkgRoot, "checkout", "--detach", [string]$lock.vcpkgBaseline) "checkout pinned vcpkg baseline"
if (-not (Test-Path -LiteralPath $vcpkgSource)) {
    if (-not (Test-Path -LiteralPath $vcpkgBootstrap)) { Fail "vcpkg bootstrap script is missing" }
    Invoke-Checked $vcpkgBootstrap @("-disableMetrics") "bootstrap vcpkg"
}
if (-not (Test-Path -LiteralPath $vcpkgSource)) { Fail "vcpkg.exe was not produced" }

Clear-ContainedDirectory $windowsBuildRoot $buildRoot "Windows build root"
New-Item -ItemType Directory -Force -Path $windowsBuildRoot | Out-Null
Invoke-Checked $git @("clone", "--recursive", [string]$lock.repository, $sourceRoot) "clone official Telegram Bot API source"
Invoke-Checked $git @("-C", $sourceRoot, "checkout", "--detach", [string]$lock.commit) "checkout pinned Telegram Bot API commit"
Invoke-Checked $git @("-C", $sourceRoot, "submodule", "sync", "--recursive") "sync Telegram submodules"
Invoke-Checked $git @("-C", $sourceRoot, "submodule", "update", "--init", "--recursive") "update Telegram submodules"
$actualCommit = (& $git -C $sourceRoot rev-parse HEAD).Trim().ToLowerInvariant()
if ($actualCommit -ne [string]$lock.commit) { Fail "Telegram source commit mismatch: $actualCommit" }

Clear-ContainedDirectory $sourceBuildRoot $windowsBuildRoot "source build root"
Clear-ContainedDirectory $stageRoot $windowsBuildRoot "stage root"
New-Item -ItemType Directory -Force -Path $sourceBuildRoot, $stageRoot, $vcpkgInstalledRoot | Out-Null
$triplet = [string]$lock.windowsVcpkgTriplet
Invoke-Checked $vcpkgSource @(
    "install",
    "--x-manifest-root=$manifestRoot",
    "--x-install-root=$vcpkgInstalledRoot",
    "--triplet=$triplet",
    "--host-triplet=x64-windows"
) "install pinned vcpkg dependencies"

$cmakeArgs = @(
    "-S", $sourceRoot,
    "-B", $sourceBuildRoot,
    "-A", "x64",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=$vcpkgRoot\scripts\buildsystems\vcpkg.cmake",
    "-DVCPKG_MANIFEST_MODE=ON",
    "-DVCPKG_MANIFEST_DIR:PATH=$manifestRoot",
    "-DVCPKG_INSTALLED_DIR:PATH=$vcpkgInstalledRoot",
    "-DVCPKG_TARGET_TRIPLET=$triplet",
    "-DVCPKG_HOST_TRIPLET=x64-windows",
    "-DOPENSSL_USE_STATIC_LIBS=TRUE",
    "-DCMAKE_POLICY_DEFAULT_CMP0091=NEW",
    "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded",
    "-DCMAKE_INSTALL_PREFIX:PATH=$stageRoot"
)
Invoke-Checked $cmake $cmakeArgs "configure Telegram Bot API"
Invoke-Checked $cmake @("--build", $sourceBuildRoot, "--target", "install", "--config", "Release", "--parallel") "build Telegram Bot API"

$built = @(Get-ChildItem -LiteralPath $stageRoot -Recurse -File -Filter "telegram-bot-api.exe")
if ($built.Count -ne 1) { Fail "expected exactly one staged telegram-bot-api.exe, found $($built.Count)" }
$builtPath = (Resolve-Path -LiteralPath $built[0].FullName).Path
& $builtPath --help *> $null
if ($LASTEXITCODE -ne 0) { Fail "telegram-bot-api.exe --help failed" }

Clear-ContainedDirectory $resourceRoot (Join-Path $WorkspaceRoot "desktop\resources") "Telegram resource root"
New-Item -ItemType Directory -Force -Path $resourceRoot | Out-Null
$destination = Join-Path $resourceRoot "telegram-bot-api.exe"
Copy-Item -LiteralPath $builtPath -Destination $destination
$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $destination).Hash.ToLowerInvariant()
$manifest = [ordered]@{
    schemaVersion = 1
    platform = "win32-x64"
    sourceCommit = ([string]$lock.commit).ToLowerInvariant()
    executable = "telegram-bot-api.exe"
    size = (Get-Item -LiteralPath $destination).Length
    sha256 = $hash
}
$manifestPath = Join-Path $resourceRoot "manifest.json"
$tempManifest = "$manifestPath.$PID.tmp"
try {
    [System.IO.File]::WriteAllText($tempManifest, (($manifest | ConvertTo-Json -Compress) + "`n"), [System.Text.UTF8Encoding]::new($false))
    Move-Item -LiteralPath $tempManifest -Destination $manifestPath -Force
} finally {
    if (Test-Path -LiteralPath $tempManifest) { Remove-Item -LiteralPath $tempManifest -Force }
}
Write-Host "OK: staged $destination ($hash)"
